language: scala
dist: trusty
os:
  - linux
scala:
  - 2.11.8
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier/
script:
  - bin/scalafmt --test
  - sbt test
  - sbt server/universal:packageBin

git:
  submodules: false

before_script:
  - 'gem install sass --version "=3.2.12"'